import Head from "next/head";
import Banner from "../src/components/Banner";
import Featured from "../src/components/Featured";
import CTA from "../src/components/CTA";
import AccountCTA from "../src/components/AccountCTA";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NaughtyBits</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />
      <CTA />
      <Featured />

      <AccountCTA />
    </div>
  );
}
